services:
  postgres:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
  web-app:
    build:
      context: web-app
      dockerfile: Dockerfile
    container_name: web-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
  server:
    build:
      context: server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=production
      - port=5000
      - database_url=postgresql://admin:password@localhost:5432/nawy?schema=public
