version: "3.8"
services:
  postgres:
    container_name: nawy-postgres
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nawy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d nawy"]
      interval: 1s
      timeout: 15s
      retries: 5

  server:
    container_name: nawy-server
    build:
      context: server
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 1s
      timeout: 15s
      retries: 10
      start_period: 5s
    environment:
      - nodeEnv=production
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/nawy?schema=public

  web-app:
    container_name: nawy-web-app
    build:
      context: web-app
      dockerfile: Dockerfile
    depends_on:
      server:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SERVER_URL=http://server:5000
